SET(CMAKE_SYSTEM_NAME qnx)
SET(CMAKE_SYSTEM_VERSION 1)

# specify the cross compiler
SET(CMAKE_C_COMPILER   $ENV{QNX_HOST}/usr/bin/ntoarmv7-gcc)
SET(CMAKE_CXX_COMPILER $ENV{QNX_HOST}/usr/bin/ntoarmv7-g++)


# where is the target environment 
SET(CMAKE_FIND_ROOT_PATH $ENV{QNX_HOST} $ENV{QTDIR} $ENV{QNX_TARGET} $ENV{QNX_TARGET}/armle-v7)

SET(CMAKE_STATIC_LIBRARY_PREFIX "")
SET(CMAKE_SHARED_LIBRARY_PREFIX "lib")
SET(CMAKE_STATIC_LIBRARY_SUFFIX ".a")
SET(CMAKE_SHARED_LIBRARY_SUFFIX ".so")
SET(CMAKE_FIND_LIBRARY_PREFIXES "lib")
SET(CMAKE_FIND_LIBRARY_SUFFIXES ".so" ".a")

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)

#Force -pfPIC when ompiling.
SET(CMAKE_C_FLAGS -fPIC)
